<h1 style="color: red; text-align: center;">Practical 6: Vectors Part</h1>

<h2 style="color: red;">Instructor: Dr. Khaled Mohamad</h2>

In [64]:
import pandas as pd
import seaborn as sns
import matplotlib as plt
import numpy as np

# Q1. Create a Python list representing vector v = [2, -1, 3] and multiply it by scalar 4.

1. Show the output.
2. Explain why the result is incorrect from a linear algebra perspective.
3. Convert the vector to a NumPy array and repeat the operation.

### Answer 1

In [65]:
v = [2, -1, 3]
v *= 4
print(v)

[2, -1, 3, 2, -1, 3, 2, -1, 3, 2, -1, 3]


### Explanation:...

In python when we are multiplying the list by number it just copies itself it the times of  the scalar

# Q2. Given vector a = [5, -3] and scalar $\lambda$ = -2:

1. Compute λa.
2. Compare their magnitudes
3. Explain the effect on magnitude and direction.

Hint: to write $\lambda$ in markdown syntax, do the following:


$\lambda $

### Answer 2

In [66]:
a = np.array([5, -3])
alpha = -2

a_alpha = a * alpha
print(a_alpha)

a_magnitude = np.linalg.norm(a)
a_alpha_magnitude = np.linalg.norm(a_alpha)
print("a_magnitude: ", a_magnitude)
print("a_aplha_magnnitude", a_alpha_magnitude)


[-10   6]
a_magnitude:  5.830951894845301
a_aplha_magnnitude 11.661903789690601


### Explanation:...

After multiplyuing vector by the sclalar it's magnitude increased by scalar velue which is 2.

# Q3. Create:

- Column vector shape (3,1)
- Row vector shape (1,4)
- Print the shape of the results

Add them using NumPy broadcasting.
### Answer 3

In [67]:
col = np.array([
    [3],
    [1]
])
row = np.array([[1, 4]])

print("Col shape: ", col.shape)
print("Row shape: ", row.shape)

broadcast_res = col + row
print("Broadcasted: ", broadcast_res)

Col shape:  (2, 1)
Row shape:  (1, 2)
Broadcasted:  [[4 7]
 [2 5]]


# Q4 . Create vector v = [1,2,3,4] and add scalar 5.
Explain why NumPy allows this.
### Answer 4

In [68]:
v = np.array([1,2,3,4,5])
print(v + 5)

[ 6  7  8  9 10]


### Explanation: ...

Because of the broadcasting. it expands scalar to [5,5,5,5,5]

# Q5. Given vector a = [1,2,3,4,5,6], compute its
Euclidean norm manually and using NumPy.

Hint: By "manually," I mean solving it step by step using only basic NumPy functions.
### Answer 5

In [78]:
a = np.array([1, 2, 3, 4, 5, 6])

sum_a_sq = 0
for num in a:
    sum_a_sq += num * num
print(sum_a_sq**0.5)

print(np.linalg.norm(a))

# np.qsrt(sum(np.multuply(a, a)))

9.539392014169456
9.539392014169456


# Q6. Generate a random vector of length 10 and normalize it. Print the norm before and after normalization
### Answer 6

In [70]:
v = np.random.rand(10)

norm_before = np.linalg.norm(v)

v_normalized = v / norm_before

print("Before: ", norm_before)
print("After: ", np.linalg.norm(v_normalized))

Before:  1.8868020237189438
After:  1.0


# Q7. Compute the dot product of vectors
a = [1,2,3,4,5,6] & b = [0,-4,3,-3,6,5]
using:
1. Manual loop
2. NumPy np.dot() .
### Answer 7

In [71]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([0, -4, 3, -3, 6, 5])
manual = 0
for num1, num2 in zip(a, b):
    manual  += num1 * num2
print("Manual: ", manual)

print("numpy: ", np.dot(a, b))

Manual:  49
numpy:  49


# Q8. Verify the distributive property:
$$a · (b + c) = a · b + a · c$$
Hint: Generate three random numbers
### Answer 8

In [72]:
n = 5
a = np.random.randn(n)
b = np.random.randn(n)
c = np.random.randn(n)

res1 = np.dot(a,b) + np.dot(a,c)
res2 = np.dot(a, (b+c))
print([res1, res2])

[-2.965188643937492, -2.9651886439374926]


# Q9: Compute the Euclidean distance matrix between every point in group A and every point in group B.
# Group A
A = np.array([

[ 2, 1],

[ 5, 4],

[ 1, 6],

[ 7, 2]

])
# Group B
B = np.array([

[0, 0],

[6, 3],

[3, 5]

])

In [73]:
A = np.array([
[ 2, 1],
[ 5, 4],
[ 1, 6],
[ 7, 2]
])
B = np.array([
[0, 0],
[6, 3],
[3, 5]
])
print(A.shape, B.shape)

(4, 2) (3, 2)


In [74]:
A = A[:, np.newaxis, :]
B = B[np.newaxis, :, :]
print(A.shape, B.shape)

print(A)

print(B)

(4, 1, 2) (1, 3, 2)
[[[2 1]]

 [[5 4]]

 [[1 6]]

 [[7 2]]]
[[[0 0]
  [6 3]
  [3 5]]]


In [75]:
diff = A - B
print(diff)

[[[ 2  1]
  [-4 -2]
  [-1 -4]]

 [[ 5  4]
  [-1  1]
  [ 2 -1]]

 [[ 1  6]
  [-5  3]
  [-2  1]]

 [[ 7  2]
  [ 1 -1]
  [ 4 -3]]]


In [76]:
sum_diff = np.sum(diff**2, axis=2) #-1
print(sum_diff)

[[ 5 20 17]
 [41  2  5]
 [37 34  5]
 [53  2 25]]


In [77]:
diff_matrix = np.sqrt(sum_diff)
print(diff_matrix)

[[2.23606798 4.47213595 4.12310563]
 [6.40312424 1.41421356 2.23606798]
 [6.08276253 5.83095189 2.23606798]
 [7.28010989 1.41421356 5.        ]]
